---

- name: APT | Install apt-transport-https
  apt: pkg=apt-transport-https update_cache=yes cache_valid_time=3600

- name: APT_KEY | Add MariaDB GPG key
  apt_key: >
    url=https://downloads.mariadb.com/MaxScale/MariaDB-MaxScale-GPG-KEY
    state=present

- name: APT_REPOSITORY | Add MariaDB Maxscale repo
  apt_repository: >
    repo='deb https://downloads.mariadb.com/MaxScale/{{ maxscale_version }}/debian {{ ansible_distribution_release }} main'
    state=present

- name: APT | Install Maxscale from deb package
  apt: pkg=maxscale state=present

- name: COMMAND | Deploy init script
  command: cp /usr/share/maxscale/maxscale /etc/init.d/maxscale
  args:
    creates: /etc/init.d/maxscale
  when: ansible_service_mgr == 'sshd'
