---

- name: INCLUDE | Install
  include: install.yml

- name: TEMPLATE | Deploy maxcale configuration
  template: >
    src=etc/maxscale.cnf.j2
    dest=/etc/maxscale.cnf
    mode=0640
    owner=maxscale
  notify: reload maxscale

- name: TEMPLATE | Prepare logrotate
  template: >
    src=etc/logrotate.d/maxscale.j2
    dest=/etc/logrotate.d/maxscale
  when: maxscale_logrotate

- name: SERVICE | Ensure Maxscale is enabled and started
  service: name=maxscale state=started enabled=yes
  when: ansible_service_mgr == 'systemd'
